/*
 * User-create form
 */
package project.GUI;
import back.users.Librarians;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.InstanceAlreadyExistsException;
import javax.swing.JOptionPane;
/**
 *
 * @author Farit Galeev
 */
public class UserCreate extends javax.swing.JFrame {

    /**
     * Creates new form UserCreate
     */
    public UserCreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phoneF = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        statusBar = new javax.swing.JComboBox<>();
        addressF = new javax.swing.JTextField();
        nameF = new javax.swing.JTextField();
        snameF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GLib");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add user to the system");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 420, 60));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");
        jLabel3.setName(""); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, 60));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Surname");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 220, 60));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 220, 60));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 60));

        phoneF.setBackground(new java.awt.Color(0, 204, 204));
        phoneF.setBorder(null);
        phoneF.setForeground(new java.awt.Color(255, 255, 255));
        try {
            phoneF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+#-###-###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneF.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jPanel1.add(phoneF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 200, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 250, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 250, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 250, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 250, 10));

        statusBar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Faculty", "Librarian" }));
        jPanel1.add(statusBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 290, 30));

        addressF.setBackground(new java.awt.Color(0, 204, 204));
        addressF.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addressF.setForeground(new java.awt.Color(255, 255, 255));
        addressF.setText("Address");
        addressF.setBorder(null);
        addressF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressFMouseClicked(evt);
            }
        });
        addressF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFActionPerformed(evt);
            }
        });
        jPanel1.add(addressF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 200, 40));

        nameF.setBackground(new java.awt.Color(0, 204, 204));
        nameF.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        nameF.setForeground(new java.awt.Color(255, 255, 255));
        nameF.setText("Name");
        nameF.setBorder(null);
        nameF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameFMouseClicked(evt);
            }
        });
        nameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFActionPerformed(evt);
            }
        });
        jPanel1.add(nameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 200, 40));

        snameF.setBackground(new java.awt.Color(0, 204, 204));
        snameF.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        snameF.setForeground(new java.awt.Color(255, 255, 255));
        snameF.setText("Surname");
        snameF.setBorder(null);
        snameF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                snameFMouseClicked(evt);
            }
        });
        snameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameFActionPerformed(evt);
            }
        });
        jPanel1.add(snameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 200, 40));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cancel");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 180, 50));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 220, 60));

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8jPanel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFActionPerformed

    private void nameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFActionPerformed

    private void snameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameFActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
    
    }//GEN-LAST:event_jPanel2MouseClicked

    
    private void nameFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameFMouseClicked
        nameF.setText("");
    }//GEN-LAST:event_nameFMouseClicked

    private void snameFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snameFMouseClicked
      snameF.setText("");
    }//GEN-LAST:event_snameFMouseClicked

    private void addressFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressFMouseClicked
      addressF.setText("");
    }//GEN-LAST:event_addressFMouseClicked

    //create form that show to user his Login and Password and write down personal data in LMS DB
    private void jLabel8jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8jPanel2MouseClicked
        try {
            // TODO add your handling code here:
            Librarians lib = new Librarians();
            String[] lp = lib.generateLogin(nameF.getText(), snameF.getText());
            lib.addPerson(nameF.getText(), snameF.getText(), addressF.getText(),phoneF.getText().replaceAll("-", ""), (String) statusBar.getSelectedItem());
            JOptionPane.showMessageDialog(null, "Please write down your LogIn and Password\n"+
                                            "LogIn: " + lp[0] + "\n" +
                                            "Password: " + lp[1] + "\n");
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Some fields are empty");
        } catch (InstanceAlreadyExistsException ex) {
            JOptionPane.showMessageDialog(null, "This person is already exist");
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Wrong Phone Number");
        }
        
    }//GEN-LAST:event_jLabel8jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked
//cancel button that close user-create form
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField nameF;
    private javax.swing.JFormattedTextField phoneF;
    private javax.swing.JTextField snameF;
    private javax.swing.JComboBox<String> statusBar;
    // End of variables declaration//GEN-END:variables
}
