/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Farit Galeev
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Glib = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        statbox = new javax.swing.JComboBox<>();
        sep2 = new javax.swing.JSeparator();
        sep1 = new javax.swing.JSeparator();
        loginf = new javax.swing.JTextField();
        passf = new javax.swing.JPasswordField();
        enterb = new javax.swing.JPanel();
        enter = new javax.swing.JLabel();
        login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GLib");
        setBounds(new java.awt.Rectangle(759, 601, 759, 759));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(769, 601));
        setMinimumSize(new java.awt.Dimension(769, 601));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${defaultCloseOperation}"), this, org.jdesktop.beansbinding.BeanProperty.create("defaultCloseOperation"));
        bindingGroup.addBinding(binding);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(761, 585));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Glib.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Glib.setForeground(new java.awt.Color(255, 255, 255));
        Glib.setText("Gogol Libraries LMS");
        jPanel2.add(Glib, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 450, 70));

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/book (1).png"))); // NOI18N
        label.setText("jLabel7");
        jPanel2.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 260, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 600));

        pass.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 310, 30));

        status.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Status");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 310, 70));

        statbox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        statbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Librarian", "Faculty", "Student" }));
        jPanel1.add(statbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 280, 40));

        sep2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 280, 30));

        sep1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 280, 20));

        loginf.setBackground(new java.awt.Color(0, 102, 204));
        loginf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        loginf.setForeground(new java.awt.Color(255, 255, 255));
        loginf.setText("Enter your login");
        loginf.setBorder(null);
        loginf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginfMouseClicked(evt);
            }
        });
        loginf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginfActionPerformed(evt);
            }
        });
        jPanel1.add(loginf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 280, 50));

        passf.setBackground(new java.awt.Color(0, 102, 204));
        passf.setForeground(new java.awt.Color(255, 255, 255));
        passf.setText("jPasswordField1");
        passf.setBorder(null);
        passf.setCaretColor(new java.awt.Color(255, 255, 255));
        passf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passfFocusGained(evt);
            }
        });
        jPanel1.add(passf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 280, 30));

        enterb.setBackground(new java.awt.Color(0, 204, 204));
        enterb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterbMouseClicked(evt);
            }
        });
        enterb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enter.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        enter.setForeground(new java.awt.Color(255, 255, 255));
        enter.setText("Enter");
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterbMouseClicked(evt);
            }
        });
        enterb.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, 40));

        jPanel1.add(enterb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 180, 60));

        login.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LogIn");
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 310, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginfActionPerformed

    private void loginfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginfMouseClicked
        loginf.setText("");
    }//GEN-LAST:event_loginfMouseClicked

    private void passfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passfFocusGained
        passf.setText("");
    }//GEN-LAST:event_passfFocusGained

    private void enterbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterbMouseClicked
        //обращение к базе данных для проверки существования пользователя
        if(statbox.getSelectedItem().equals("Librarian") && loginf.getText().equals("admin") && passf.getText().equals( "admin")){
            dispose();
            Librarian lib = new Librarian();
            lib.setLocationRelativeTo(null);
            lib.setVisible(true);
        }   else{
        if(statbox.getSelectedItem().equals("Student") && loginf.getText().equals("student") && passf.getText().equals( "student")){
            dispose();
            Student st = new Student();
            st.setLocationRelativeTo(null);
            st.setVisible(true);
        } else{ 
        if(statbox.getSelectedItem().equals("Faculty") && loginf.getText().equals("faculty") && passf.getText().equals( "faculty")){
            dispose();
            Faculty fc = new Faculty();
            fc.setLocationRelativeTo(null);
            fc.setVisible(true);
        } 
          else{
                   JOptionPane.showMessageDialog(null, "Incorrect Status or LogIn or Password", "ERROR", JOptionPane.PLAIN_MESSAGE);
                   }
        }
        }
    }//GEN-LAST:event_enterbMouseClicked
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Glib;
    private javax.swing.JLabel enter;
    private javax.swing.JPanel enterb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel login;
    private javax.swing.JTextField loginf;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passf;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JComboBox<String> statbox;
    private javax.swing.JLabel status;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
